### ISSUE TITLE
wikipedia.exceptions.DisambiguationError

### ISSUE THREAD

**Issue by dboudro** [dboudro/dboudro.github.io#1]
my scraping (scraper.py) stops after about 5 plant pages due to there being a disambiguation page  (multiple results for one plant name).

We discussed using the href to get an exact page, which I am able to do via
`plants.append(li.find('a')['href'])`
instead of `plants.append(li.find('a')[0].contents)`

however.  the wikipedia.page() function loads a page via its title or pageid, not via the href.  I cannot find a function to load href pages on the wikipedia API I am using.

My second line of action was to try to work with the 
wikipedia.exceptions.DisambiguationError
which has a 'property' called options.  I was thinking I could say if you get this error, than choose the first page.

Would very much appreciate your insight--I'm a bit stuck!

Thanks,

-Dylan

**Comment by dboudro** [comment]
Here are the relevant API's:

[Wikpedia API](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#quick-start)

[Beautiful Soup](https://wikipedia.readthedocs.io/en/latest/code.html#module-wikipedia.exceptions)

**Comment by davelandry** [comment]
Hmm, interesting predicament. What about using the "title" attribute that's on the <a> tag? Maybe that's more explicit than the contents of the tag itself? Something like:

``` py
plants.append(li.find('a')['title'])
```

If that doesn't work, which one is the first one to get tripped up?

**Comment by dboudro** [comment]
that appears to have worked! 

still tripping up, but for other reasons I believe I can solve, thus far.

Thanks!

**Comment by davelandry** [comment]
Hey @dboudro, haven't heard from you in a while. Were you able to get the data scraper working? If we can't get a page rendered from real data soon, you might have to pivot to a smaller dataset.

**Comment by dboudro** [comment]
Hey @davelandry!  

Here's a big update on whats been happening with the dev & design process:

I have the scraper collecting plant name and species on all 2000 plants.  I've coded it to grab more fields (genus, order, etc.)  and it works. I just need to complete a run of it on all 2000 plants .

 In terms of displaying real data--I'm working on setting up d3.csv and d3.csv.parse (d3.v3 :/) 

I've also redesigned the page using feedback from our critique / to further extend the book metaphor in how the info is displayed.

I will try to have a page rendered from real data by Sunday!

**Comment by dboudro** [comment]
Here's a screenshot of the new design: 
<img width="1209" alt="screen shot 2016-11-18 at 11 20 30 pm" src="https://cloud.githubusercontent.com/assets/4648917/20452990/ce8c6e92-ade5-11e6-8390-1eca00b98213.png">

**Comment by davelandry** [comment]
Looks good! Any reason why you're using d3 v3 and not v4?

**Comment by dboudro** [comment]
Yup, the dendrogram is coded in v3 and doesn't work in v4 (I suppose I could tweak it).

Unfortunately the support for csv parsing looks a lot better in v4 but hopefully I can figure it out in v3 too.

**Comment by davelandry** [comment]
Where'd you find that dendrogram code? You should definitely use v4 for the dendrogram. Mike Bostock has updated his examples as well:
- https://github.com/d3/d3-hierarchy#tree
- http://bl.ocks.org/mbostock/4339184

Generally, when updating to v4, the rule of thumb is that all of his functions are now only one level down inside of the object. For example, all instances of `d3.layout.tree` are now just `d3.tree`.

**Comment by dboudro** [comment]
https://bl.ocks.org/mbostock/4339083
is the one I'm using.  I'll try changing the functions to be one level down and see if I can get it working!  I do appreciate how the v3 example is collapsable so ideally I can mod this one to get it to work with v4.
