### ISSUE TITLE
Encapsulation Problem with the parsed CSV Data

### ISSUE THREAD

**Issue by dboudro** [dboudro/dboudro.github.io#2]
Hi @DaveLandry,

Hope you are having an awesome holiday break--enjoying Brazil?

I currently have the CSV data outputting to the console as an Array of objects.  

The problem is I'm having trouble accessing the Array of objects from outside of the d3.csv function.  

<img width="733" alt="screen shot 2016-11-25 at 4 56 43 pm" src="https://cloud.githubusercontent.com/assets/4648917/20635836/ae3043d0-b330-11e6-8a97-b6ac0788b75c.png">

console.log(rows) : 
<img width="247" alt="screen shot 2016-11-25 at 5 49 10 pm" src="https://cloud.githubusercontent.com/assets/4648917/20636257/983e5f60-b337-11e6-9823-d47093875050.png">

Because the array of objects is this argument rows.. I can't seem to figure out how to store it in a javascript object that I can reference from anywhere in the DOM.

I'm thinking I need to make an accessor function or something?  Would appreciate your help.

Thank you,

-Dylan

**Comment by dboudro** [comment]
I just find it weird that I can't reference the array of data.

I would have expected output to be the array.  OR output.getRows(error, rows) but I can't call that function I believe because error and rows are arguments that only exist within D3

**Comment by davelandry** [comment]
Not sure why you're passing that second function that will only return the ID of each plant, but you can make the loaded data globally accessible by declaring a variable outside of the csv function, and then overriding it with the loaded data:

```js
var globalData;
d3.csv("plantOutput.csv", function(error, data) {
  globalData = data;
  // now call a function that will do something with that data
});

**Comment by dboudro** [comment]
got it, thank you!

And the second function was for testing something earlier... just deleted it.

**Comment by davelandry** [comment]
Please try and have your page populated with data from the CSV by Tuesday. I've set aside some time tomorrow morning to sort of be "on call" if you run into any more roadblocks.
